2014/09/18 12:53:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "about".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('about')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testapp/about
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/site/contact
---
2014/09/18 12:59:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('page')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testapp/about
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/site/index
---
2014/09/18 13:06:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "contact" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('contact')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/contact
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/about
---
2014/09/18 13:06:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "login" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('login')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/login
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/contact
---
2014/09/18 13:06:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "contact" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('contact')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/contact
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/about
---
2014/09/18 13:07:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "contact" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('contact')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/contact
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/site/index
---
2014/09/18 13:07:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "index" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('index')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/index
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/about
---
2014/09/18 13:07:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "index" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('index')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/index
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/about
---
2014/09/18 13:07:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "contact" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('contact')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/contact
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/about
---
2014/09/18 13:07:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "login" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('login')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/login
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/contact
---
2014/09/18 13:07:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "contact" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('contact')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/contact
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/login
---
2014/09/18 13:07:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "index" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('index')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/index
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/about
---
2014/09/18 13:09:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "login" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('login')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/login
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/index
---
2014/09/18 13:09:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "contact" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('contact')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/contact
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/login
---
2014/09/18 13:09:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "index" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('index')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/index
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/about
---
2014/09/18 13:09:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "contact" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('contact')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/contact
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/about
---
2014/09/18 13:09:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "index" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('index')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/index
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/about
---
2014/09/18 13:09:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "contact" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('contact')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/contact
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/index
---
2014/09/18 13:10:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "contact" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('contact')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/contact
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/index
---
2014/09/18 13:18:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "contact" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('contact')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/contact
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/site/page?view=about
---
2014/09/18 13:18:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "contact" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('contact')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/contact
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/about
---
2014/09/18 13:18:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "login" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('login')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/login
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/contact
---
2014/09/18 13:18:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "contact" was not found.' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('contact')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('page')
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testapp/contact
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/login
---
2014/09/18 13:20:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "about".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(270): CController->missingAction('about')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('about')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/about')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/about
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/
---
2014/09/18 14:32:12 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/gii
---
2014/09/18 14:37:24 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/gii
---
2014/09/18 14:39:17 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:39:33 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:39:35 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:41:06 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:41:48 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:41:53 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:43:34 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:43:35 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:43:35 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:43:35 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:43:35 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:43:36 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:43:36 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:43:36 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:43:36 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:43:36 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:43:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:43:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:43:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-tivun.dev5.oxagile.com/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/index.php?r=gii
---
2014/09/18 14:46:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /var/www/yii-tivun.dev5.oxagile.com/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testapp/gii/model/index
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/gii/default/index
---
2014/09/18 14:53:54 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2003] Can't connect to MySQL server on 'dev5.oxagile.com' (111)' in /var/www/yii-tivun.dev5.oxagile.com/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testapp/gii/model/index
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/gii/default/index
---
2014/09/18 14:54:01 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2003] Can't connect to MySQL server on 'dev5.oxagile.com' (111)' in /var/www/yii-tivun.dev5.oxagile.com/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testapp/gii/model/index
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/gii/default/index
---
2014/09/18 15:02:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'192.168.32.108' (using password: NO)' in /var/www/yii-tivun.dev5.oxagile.com/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testapp/gii/model/index
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/gii/default/index
---
2014/09/18 15:17:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "create".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(270): CController->missingAction('create')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('create')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('employee/create')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/employee/create
---
2014/09/18 15:17:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "create".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(270): CController->missingAction('create')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('create')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('employee/create')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/employee/create/
---
2014/09/18 15:17:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "view".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(270): CController->missingAction('view')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('view')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('employee/view')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/employee/view
---
2014/09/18 15:17:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "create".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(270): CController->missingAction('create')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('create')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('employee/create')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/employee/create/
---
2014/09/18 15:17:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "create".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(270): CController->missingAction('create')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('create')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('employee/create')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/employee/create
---
2014/09/18 15:18:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(270): CController->missingAction('index.php')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('index.php')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('employee/index....')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/employee/index.php
---
2014/09/18 15:18:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "create.php".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(270): CController->missingAction('create.php')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('create.php')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('employee/create...')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/employee/create.php
---
2014/09/18 15:18:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(270): CController->missingAction('index.php')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('index.php')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('employee/index....')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/employee/index.php
---
2014/09/18 15:20:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "create".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(270): CController->missingAction('create')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('create')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('employee/create')
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testapp/employee/create
---
2014/09/18 15:21:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testapp/index.php?r=user/admin
---
2014/09/18 18:40:41 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "contract".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php:878
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(782): CController->renderPartial('contract', Array, true)
#1 /var/www/yii-tivun.dev5.oxagile.com/testapp/protected/controllers/SiteController.php(125): CController->render('contract', Array)
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CInlineAction.php(49): SiteController->actionContract()
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('contract')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contract')
#8 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/testapp/site/contract
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/contact
---
2014/09/18 18:53:18 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "contract".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php:878
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(782): CController->renderPartial('contract', Array, true)
#1 /var/www/yii-tivun.dev5.oxagile.com/testapp/protected/controllers/SiteController.php(125): CController->render('contract', Array)
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CInlineAction.php(49): SiteController->actionContract()
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('contract')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contract')
#8 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/testapp/site/contract
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/
---
2014/09/18 18:55:00 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "contract".' in /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php:878
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(782): CController->renderPartial('contract', Array, true)
#1 /var/www/yii-tivun.dev5.oxagile.com/testapp/protected/controllers/SiteController.php(125): CController->render('contract', Array)
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CInlineAction.php(49): SiteController->actionContract()
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('contract')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contract')
#8 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/testapp/site/contract
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/
---
2014/09/18 18:58:40 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.contract" is not defined.' in /var/www/yii-tivun.dev5.oxagile.com/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CModule.php(105): CComponent->__get('contract')
#1 /var/www/yii-tivun.dev5.oxagile.com/testapp/protected/controllers/SiteController.php(121): CModule->__get('contract')
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CInlineAction.php(49): SiteController->actionContract()
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): CController->run('contract')
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contract')
#8 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/testapp/site/contract
HTTP_REFERER=http://yii-tivun.dev5.oxagile.com/testapp/site/contract
---
2014/10/02 14:36:51 [error] [php] include(ContractForm.php): failed to open stream: No such file or directory (/var/www/yii-tivun.dev5.oxagile.com/framework/YiiBase.php:427)
Stack trace:
#0 /var/www/yii-tivun.dev5.oxagile.com/testapp/protected/controllers/SiteController.php(115): spl_autoload_call()
#1 /var/www/yii-tivun.dev5.oxagile.com/framework/web/actions/CInlineAction.php(49): SiteController->actionContract()
#2 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(308): CInlineAction->runWithParams()
#3 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(286): SiteController->runAction()
#4 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CController.php(265): SiteController->runActionWithFilters()
#5 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(282): SiteController->run()
#6 /var/www/yii-tivun.dev5.oxagile.com/framework/web/CWebApplication.php(141): CWebApplication->runController()
#7 /var/www/yii-tivun.dev5.oxagile.com/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php(13): CWebApplication->run()
REQUEST_URI=/testapp/site/contract
in /var/www/yii-tivun.dev5.oxagile.com/testapp/protected/controllers/SiteController.php (115)
in /var/www/yii-tivun.dev5.oxagile.com/testapp/index.php (13)
